export const ALL_IMAGES = [
  { src: "abstract-landscape-1.png", alt: "Abstract Digital Landscape" },
  { src: "cosmic-vessel-2.png", alt: "Cosmic Vessel Digital Art" },
  { src: "surreal-geometry-3.png", alt: "Surreal Geometric Forms" },
  { src: "ethereal-waves-4.png", alt: "Ethereal Wave Patterns" },
  { src: "digital-vessel-5.png", alt: "Digital Vessel Creation" },
  { src: "unreal-horizon-6.png", alt: "Unreal Horizon Vista" },
  { src: "ethereal-structures-7.png", alt: "Ethereal Architectural Forms" },
  { src: "cosmic-geometry-8.png", alt: "Cosmic Geometric Patterns" },
  { src: "digital-dreams-9.png", alt: "Dreamlike Digital Compositions" },
  { src: "surreal-vessels-10.png", alt: "Surreal Vessel Interpretations" },
  { src: "abstract-reality-11.png", alt: "Abstract Reality Concepts" },
  { src: "unreal-dimensions-12.png", alt: "Dimensional Art Pieces" },
  { src: "floating-forms-13.png", alt: "Floating Geometric Forms" },
  { src: "mystic-landscapes-14.png", alt: "Mystical Landscape Art" },
  { src: "digital-horizons-15.png", alt: "Digital Horizon Vistas" },
  { src: "cosmic-waves-16.png", alt: "Cosmic Wave Patterns" },
  { src: "ethereal-visions-17.png", alt: "Ethereal Visual Concepts" },
  { src: "surreal-depths-18.png", alt: "Deep Surreal Compositions" },
  { src: "abstract-vessels-19.png", alt: "Abstract Vessel Designs" },
  { src: "digital-realms-20.png", alt: "Digital Realm Landscapes" },
  { src: "unreal-cosmos-21.png", alt: "Cosmic Unreal Scenes" },
  { src: "floating-dreams-22.png", alt: "Floating Dream Imagery" },
  { src: "mystic-geometry-23.png", alt: "Mystical Geometric Art" },
  { src: "ethereal-infinity-24.png", alt: "Infinite Ethereal Concepts" },
];
